apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "chirpstack.fullname" . }}-gatewaybridge
data:
   INTEGRATION__MQTT__AUTH__GENERIC__SERVERS: tcp://{{ include "chirpstack.fullname" . }}-mosquitto:1883
