apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "chirpstack.fullname" . }}-networkserver
data:
     POSTGRESQL__DSN: "postgres://chirpstack_ns:chirpstack_ns@{{ include "chirpstack.fullname" . }}-postgresql/chirpstack_ns?sslmode=disable"
     REDIS__URL: redis://{{ include "chirpstack.fullname" . }}-redis-master:6379
     NETWORK_SERVER__BAND__NAME: EU868
     {{- if  .Values.mosquitto.external }}
     NETWORK_SERVER__GATEWAY__BACKEND__MQTT__SERVER: {{ .Values.mosquitto.external_address }}
     {{ else }}
     NETWORK_SERVER__GATEWAY__BACKEND__MQTT__SERVER: tcp://{{ include "chirpstack.fullname" . }}-mosquitto:{{ .Values.mosquitto.service.port }}
     {{- end }}
     JOIN_SERVER__DEFAULT__SERVER: http://{{ include "chirpstack.fullname" . }}-applicationserver:8003
     GEOLOCATION_SERVER__SERVER: {{ include "chirpstack.fullname" . }}-geolocationserver:8005
