apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "chirpstack.fullname" . }}-gatewaybridge
data:
   {{- if  .Values.mosquitto.external }}
   INTEGRATION__MQTT__AUTH__GENERIC__SERVERS: {{ .Values.mosquitto.external_address }}
   {{ else }}
   INTEGRATION__MQTT__AUTH__GENERIC__SERVERS: tcp://{{ include "chirpstack.fullname" . }}-mosquitto:{{ .Values.mosquitto.service.port }}
   {{- end }}
