apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chirpstack.fullname" . }}-gatewaybridge
  labels:
    {{- include "chirpstack.labels" . | nindent 4 }}
    app.kubernetes.io/instance: "gatewaybridge"
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "chirpstack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/instance: "gatewaybridge"
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-gatewaybridge.yaml") . | sha256sum }}
      labels:
        {{- include "chirpstack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/instance: "gatewaybridge"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chirpstack.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.gatewaybridge.image.repository }}:{{ .Values.gatewaybridge.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
               name: {{ include "chirpstack.fullname" . }}-gatewaybridge
          volumeMounts:
          - name: config-volume
            mountPath: /etc/chirpstack-gateway-bridge/gateway-bridge.toml
            subPath: gateway-bridge.toml
          ports:
            - name: gatewaybridge
              containerPort: {{ .Values.gatewaybridge.service.port }}
              protocol: UDP
            - name: metrics
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: metrics
          readinessProbe:
            httpGet:
              path: /health
              port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "chirpstack.fullname" . }}-gatewaybridge
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
