apiVersion: v1
kind: Service
metadata:
  name: {{ include "chirpstack.fullname" . }}-networkserver
  labels:
    {{- include "chirpstack.labels" . | nindent 4 }}
    app.kubernetes.io/instance: "networkserver"
spec:
  type: {{ .Values.networkserver.service.type }}
  ports:
    - port: {{ .Values.networkserver.service.port }}
      targetPort: networkserver
      protocol: TCP
      name: networkserver
  selector:
    {{- include "chirpstack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/instance: "networkserver"
