apiVersion: v1
kind: Service
metadata:
  name: {{ include "chirpstack.fullname" . }}-gatewaybridge
  labels:
    {{- include "chirpstack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gatewaybridge.service.type }}
  ports:
    - port: {{ .Values.gatewaybridge.service.port }}
      targetPort: http
      protocol: UDP
      name: http
  selector:
    {{- include "chirpstack.selectorLabels" . | nindent 4 }}
