apiVersion: v1
kind: Service
metadata:
  name: {{ include "chirpstack.fullname" . }}-applicationserver
  labels:
    {{- include "chirpstack.labels" . | nindent 4 }}
    app.kubernetes.io/instance: "applicationserver"
spec:
  type: {{ .Values.applicationserver.service.type }}
  ports:
    - port: {{ .Values.applicationserver.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - name: grpc
      port: 8001
      protocol: TCP
      targetPort: 8001
    - name: grpc2
      port: 8003
      protocol: TCP
      targetPort: 8003
  selector:
    {{- include "chirpstack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/instance: "applicationserver"
